rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx
  - ree
  - 2.0.0
  - 2.1.0
env:
  - CI_TEST=core
  - CI_TEST=cli
gemfile:
  - core/Gemfile
  - cli/gemfiles/sass_3_3.gemfile
  - cli/gemfiles/sass_master.gemfile
script: "cd $CI_TEST && bundle exec rake"
matrix:
  allow_failures:
    - rvm: rbx
  exclude:
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: 1.8.7
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: 1.8.7
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: 1.8.7
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: 1.9.2
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: 1.9.2
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: 1.9.2
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: 1.9.3
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: 1.9.3
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: 1.9.3
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: jruby-18mode
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: jruby-18mode
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: jruby-18mode
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: jruby-19mode
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: jruby-19mode
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: jruby-19mode
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: rbx
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: rbx
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: rbx
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: ree
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: ree
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: ree
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: 2.0.0
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: 2.0.0
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: 2.0.0
    - gemfile: cli/gemfiles/sass_3_3.gemfile
      env: CI_TEST=core
      rvm: 2.1.0
    - gemfile: cli/gemfiles/sass_master.gemfile
      env: CI_TEST=core
      rvm: 2.1.0
    - gemfile: core/Gemfile
      env: CI_TEST=cli
      rvm: 2.1.0
